### ISSUE TITLE
Modifying server configuration

### ISSUE THREAD

**Issue by zdenekvana** [basisai/terraform-google-vault#13]
Is there any other way how to add some changes to server configuration like e.g. exposing Prometheus metrics? There was variable **var. server_config** used in local variable **server_configuration** in **main.tf** file but it was removed in commit **0f736207**. I have to add there stuff like this:
`telemetry {
  prometheus_retention_time = "30s"
  disable_hostname = true
}`

**Comment by lawliet89** [comment]
Sorry I completely forgot about this use case. How about I add `var.server_configuration` back which expects a HCL string that is appended at the bottom of the existing configuration that the module will set up?

**Comment by zdenekvana** [comment]
It sounds good. I wasn't sure if it was removed by mistake or you wanted to force another way like e.g. add extra argument for next config file and insert the config file to the pod.

**Comment by lawliet89** [comment]
@zdenekvana can you give the changes proposed in #14 a try and see if it works for your requirements please.
